version: '3'
services:
    #Redis
    pet_all_conversation_redis:
        container_name: pet_all_conversation_redis
        image: redis
        ports:
            - 26379:6379
        networks:
            - app-network

    #MySQL Service
    pet_all_conversation_mysql:
        image: mysql:5.7.22
        command: [ 'mysqld', '--ssl=0', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=+02:00' ]
        container_name: pet_all_conversation_mysql
        restart: always
        volumes:
            - ./docker/dbdata:/var/lib/mysql
        ports:
            - '23306:3306'
        expose:
            - '23306'
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_USER_HOST=${DB_HOST}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    #Soketi
    soketi:
        container_name: 'soketi_server'
        restart: unless-stopped
        image: 'quay.io/soketi/soketi:0.34-16-debian'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        environment:
            - SOKETI_DEBUG=${SOKETI_DEBUG}
            - DEFAULT_APP_ID=${PUSHER_APP_ID}
            - DEFAULT_APP_KEY=${PUSHER_APP_KEY}
            - DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
            - PUSHER_HOST=${PUSHER_HOST}
            - PUSHER_PORT= ${PUSHER_PORT}
            - PUSHER_SCHEME=${PUSHER_SCHEME}
            - METRICS_SERVER_PORT=${METRICS_SERVER_PORT}
            - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES}
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
